name: studyu_designer_v2
description: Create digital N-of-1 studies with StudyU
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0-dev.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  cupertino_icons: ^1.0.5
  dynamic_color: ^1.6.2
  studyu_core: ^4.0.0-dev.1
  studyu_flutter_common: ^1.4.0-dev.1
  go_router: ^6.0.9
  shared_preferences: ^2.0.17
  equatable: ^2.0.5
  rxdart: ^0.27.7
  supabase: ^1.5.1
  supabase_flutter: ^1.4.0
  url_launcher: ^6.1.9
  reactive_forms: ^14.1.0 # breaking with forms_builder_validators <= 8.4.0
  reactive_color_picker: ^0.4.0 # breaking with forms_builder_validators <= 8.4.0
  form_builder_validators: ^8.4.0
  uuid: ^3.0.7
  csv: ^5.0.1
  archive: ^3.3.6
  async: ^2.10.0
  pointer_interceptor: ^0.9.3+4
  material_color_utilities: ^0.2.0
  flutter_colorpicker: ^1.0.3
  material_design_icons_flutter: ^6.0.7096

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
