name: Publish Notebook Uploader Docker image
on:
  workflow_dispatch:
  push:
    paths:
      - 'core/**'
      - 'notebook_uploader/**'
      - '.github/workflows/build-docker-notebook-uploader.yml'
    branches:
      - master
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Wait on check
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          check-name: 'Publish to Pubdev'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 600
          allowed-conclusions: success
          verbose: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          file: notebook_uploader/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/hpi-studyu/notebook-uploader:${{ github.sha }},ghcr.io/hpi-studyu/notebook-uploader:latest
